### PR TITLE
Fixed most of the PEP8 violations; added requirements.txt

### PR DESCRIPTION
**Pull request by Snaacky**
This PR attempts to move the script towards best Python practices. 

Nearly every line of the script was a [PEP8 violation](https://www.python.org/dev/peps/pep-0008/) in one way or another. Lots of missing white space after commas and operators, lack of appropriate amount of newlines around functions, bare excepts (not that except Exception is best practice or much better but at least passes PEP8), etc.

This PR doesn't touch the code itself other than `except` becoming `except Exception` so I left the PEP8 violations on line 19 and line 57 which would require code rewrites to fix.

I also added a `requirements.txt` file for easy dependency installation with `pip install -r requirements.txt`. This is also standard practice to make sure that end users are getting versions of the dependencies that work with your project as future versions may contain breaking changes.

### CODE REVIEW

**Comment by KorigamiK** [comment]
Thanks you for your contribution ! I am very new to programming and had never even herd about PEP8. You are a very kind soul, but could you kindly guide me what do I have to do to  accept your changes. 
Thanks again!

**Comment by KorigamiK** [comment]
Also what code rewrites are needed to be made for it to be free of PEP8 violations ?
Thanks.

**Comment by KorigamiK** [comment]
Also is there a way to automatically check for PEP8 violations?

**Comment by Snaacky** [comment]
>could you kindly guide me what do I have to do to accept your changes.

Seems like you managed to merge the changes which is good!

>Also what code rewrites are needed to be made for it to be free of PEP8 violations ?

The lambda expression on line 19 violates PEP8. [See this for more details](https://www.flake8rules.com/rules/E731.html). 

The variable assignment on line 57 is 113 characters. E501 recommends 79 characters. Some people ignore this rule and go up to 100-120 characters. It's a little bit tedious to decipher as is so I would clean this up and shorten it up or break it up into multiple lines if you could do it in a logical way that isn't just to cater to the PEP8 standard. [See this for more details.](https://www.flake8rules.com/rules/E501.html) 

> Also is there a way to automatically check for PEP8 violations?

This depends on what you use. [VS Code has the Python package from Microsoft](https://code.visualstudio.com/docs/languages/python). [Sublime Text has the Anaconda package](https://packagecontrol.io/packages/Anaconda). There are also some standalone Python packages [such as this one](https://pypi.org/project/pep8/). Lastly, there are also some websites [such as this one](http://pep8online.com/) that let you paste your code in and check for PEP8 violations but this is probably not that convenient.

**Pull request merged**
